SELECT Null AS 22, e.stock_id, e.id, e.id AS entry_id, e.attached, e.added_at, e.cll_doc AS _cll_doc, e.kg_doc AS _kg_doc, e.cll_rcvd AS _cll_rcvd, e.kg_rcvd AS _kg_rcvd, e.m3 AS _m3, IIf(count(le.id)>(select count(hv.id) from _HistoryView hv where entry_id = e.id),'LL','') AS _ll, (select sum(cll_doc) from _HistoryView hv where entry_id = e.id) AS sum_cll_doc, (select sum(kg_doc) from _HistoryView hv where entry_id = e.id) AS sum_kg_doc, (select sum(cll_rcvd) from _HistoryView hv where entry_id = e.id) AS sum_cll_rcvd, (select sum(kg_rcvd) from _HistoryView hv where entry_id = e.id) AS sum_kg_rcvd, (select sum(m3) from _HistoryView hv where entry_id = e.id) AS sum_m3, First(e.cll_doc)-IIf(IsNull(sum_cll_doc),0,sum_cll_doc) AS cll_doc2, First(e.kg_doc)-IIf(IsNull(sum_kg_doc),0,sum_kg_doc) AS kg_doc2, First(e.cll_rcvd)-IIf(IsNull(sum_cll_rcvd),0,sum_cll_rcvd) AS cll_rcvd2, First(e.kg_rcvd)-IIf(IsNull(sum_kg_rcvd),0,sum_kg_rcvd) AS kg_rcvd2, First(e.m3)-IIf(IsNull(sum_m3),0,sum_m3) AS m32, First(e.cll_doc)-IIf(IsNull(sum_cll_doc),0,sum_cll_doc) AS cll_doc, First(e.kg_doc)-IIf(IsNull(sum_kg_doc),0,sum_kg_doc) AS kg_doc, First(e.cll_rcvd)-IIf(IsNull(sum_cll_rcvd),0,sum_cll_rcvd) AS cll_rcvd, First(e.kg_rcvd)-IIf(IsNull(sum_kg_rcvd),0,sum_kg_rcvd) AS kg_rcvd, e.wh_number, e.ccs_number, e.consignor, e.consignee, First(e.m3)-IIf(IsNull(sum_m3),0,sum_m3) AS m3, e.damage, e.wh_pl, e.manager, e.[booking_number], e.arrival, e.description, e.status, e.situation, e.documents, e.codes, e.comments, e.container
FROM Entry AS e LEFT JOIN LoadingEntry AS le ON e.id=le.entry_id
GROUP BY e.stock_id, e.id, e.added_at, e.cll_doc, e.kg_doc, e.cll_rcvd, e.kg_rcvd, e.wh_number, e.ccs_number, e.consignor, e.consignee, e.damage, e.wh_pl, e.manager, e.[booking_number], e.arrival, e.status, e.situation, e.documents, e.description, e.codes, e.comments, e.m3, e.container, e.attached
HAVING iif(IsNull(First(e.cll_doc)),1,(First(e.cll_doc)-IIf(IsNull((select sum(cll_doc) from _HistoryView hv where entry_id = e.id)),0,(select sum(cll_doc) from _HistoryView hv where entry_id = e.id)))>0);


SELECT Null AS 22, e.stock_id, e.id, e.id AS entry_id, e.attached, e.added_at, e.cll_doc AS _cll_doc, e.kg_doc AS _kg_doc, e.cll_rcvd AS _cll_rcvd, e.kg_rcvd AS _kg_rcvd, e.m3 AS _m3, IIf(count(le.id)>first((select count_leid from _HistoryView2 where entry_id = e.id)),'LL','') AS _ll, (select sum_cll_doc from _HistoryView2 where entry_id = e.id) as sum_cll_doc, (select sum_kg_doc from _HistoryView2 where entry_id = e.id) as sum_kg_doc, (select sum_cll_rcvd from _HistoryView2 where entry_id = e.id) as sum_cll_rcvd, (select sum_kg_rcvd from _HistoryView2 where entry_id = e.id) as sum_kg_rcvd, (select sum_m3 from _HistoryView2 where entry_id = e.id) as sum_m3, first(e.cll_doc)-sum_cll_doc AS cll_doc2, first(e.kg_doc)-sum_kg_doc AS kg_doc2, first(e.cll_rcvd)-sum_cll_rcvd AS cll_rcvd2, first(e.kg_rcvd)-sum_kg_rcvd AS kg_rcvd2, first(e.m3)-sum_m3 AS m32, first(e.cll_doc)-sum_cll_doc AS cll_doc, first(e.kg_doc)-sum_kg_doc AS kg_doc, first(e.cll_rcvd)-sum_cll_rcvd AS cll_rcvd, first(e.kg_rcvd)-sum_kg_rcvd AS kg_rcvd, e.wh_number, e.ccs_number, e.consignor, e.consignee, (e.m3)-sum_m3 AS m3, e.damage, e.wh_pl, e.manager, e.[booking_number], e.arrival, e.description, e.status, e.situation, e.documents, e.codes, e.comments, e.container
FROM (Entry AS e LEFT JOIN LoadingEntry AS le ON e.id=le.entry_id)
GROUP BY e.stock_id, e.id, e.added_at, e.cll_doc, e.kg_doc, e.cll_rcvd, e.kg_rcvd, e.wh_number, e.ccs_number, e.consignor, e.consignee, e.damage, e.wh_pl, e.manager, e.[booking_number], e.arrival, e.status, e.situation, e.documents, e.description, e.codes, e.comments, e.m3, e.container, e.attached
--HAVING iif(IsNull(first(e.cll_doc)),1,(first(e.cll_doc)-((select sum_cll_doc from _HistoryView2 where entry_id = e.id)))>0);


(select sum_cll_doc from _HistoryView2 hv where hv.entry_id = e.id)
(select sum_kg_doc from _HistoryView2 hv where hv.entry_id = e.id)
(select sum_cll_rcvd from _HistoryView2 hv where hv.entry_id = e.id)
(select sum_kg_rcvd from _HistoryView2 hv where hv.entry_id = e.id)
(select sum_m3 from _HistoryView2 hv where hv.entry_id = e.id)